/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Monkroose.gltf -o src/components/Monkroose.gltf -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Monkroose({hovered, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Monkroose.gltf')
  const { actions } = useAnimations(animations, group)

  console.log(actions)
  useEffect(() => {
    const anim = hovered ? "Wave": "Idle"
    actions[anim].reset().fadeIn(0.5).play()
    return () => actions[anim].fadeOut(0.5)
  }, [hovered])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Monkroose" geometry={nodes.Monkroose.geometry} material={materials.Material} skeleton={nodes.Monkroose.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Monkroose.gltf')
